def convertir_fahrenheit (F):
    return ((F - 32) * 5 / 9)
print ("______________________")
print ("|", convertir_fahrenheit (0),"|")
print ("______________________")
print ("|", convertir_fahrenheit (10),"|")
print ("______________________")
print ("|", convertir_fahrenheit (20),"|")
print ("______________________")
print ("|", convertir_fahrenheit (30),"|")
print ("______________________")
print ("|", convertir_fahrenheit (40),"  |")
print ("______________________")
print ("|", convertir_fahrenheit (50),"              |")
print ("______________________")
print ("|", convertir_fahrenheit (60),"|")
print ("______________________")
print ("|", convertir_fahrenheit (70),"  |")
print ("______________________")
print ("|", convertir_fahrenheit (80),"|")
print ("______________________")
print ("|", convertir_fahrenheit (90),"  |")
print ("______________________")
print ("|", convertir_fahrenheit (100),"  |")
print ("______________________")
print ("|", convertir_fahrenheit (110),"|")
print ("______________________")
print ("|", convertir_fahrenheit (120),"|")
print ("______________________")
print ("       listo :D       ")